[data_sources.uniswap]
# Please set these in .env
 pool_address = ""
 websocket_url = ""
abi_path = "src/contracts/uniswap_abi.json"
decimal_token0 = 6  # USDC decimals
decimal_token1 = 18 # ETH decimals
data_retention_seconds = 21600 #we specify 6 hours as default

[data_sources.kraken]
trading_pair = "ETH/USD"
ws_buffer_size = 100

[output]
data_dir = "data"
volatility_file = "volatility.csv"

[output.trade_files]
kraken = "kraken_trades.csv"
uniswap = "uniswap_trades.csv"

[output.vwap_files]
kraken = "kraken_vwap.csv"
uniswap = "uniswap_vwap.csv"

[cleaning]
mean_window = 100
std_dev_threshold = 3.0
min_volume = 0.0001
max_volume = 1000.0

[volatility]
cex_weight = 0.7
dex_weight = 0.3
annualization_factor = 525600.0 #mins in a year
return_type = "LogReturns"

windows = [
    { name = "micro", length_seconds = 300, sampling_interval = 60 },    # 5 mins
    { name = "short", length_seconds = 1800, sampling_interval = 60 },   # 30 mins
    { name = "daily", length_seconds = 86400, sampling_interval = 300 }, # 24 hrs
]